/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javapro;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class BookFrom extends javax.swing.JFrame {
PreparedStatement ps = null;
    ResultSet rs = null;
    Connection con = javaconnect.connectdb();
    /**
     * Creates new form booksFrom
     */
    public BookFrom() {
        initComponents();
        javaconnect.connectdb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        subjectradio = new javax.swing.JRadioButton();
        titleradio = new javax.swing.JRadioButton();
        authorradio = new javax.swing.JRadioButton();
        idradio = new javax.swing.JRadioButton();
        isbnradio = new javax.swing.JRadioButton();
        searchfield = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Title", "Author", "ID", "ISBN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("Search for");

        buttonGroup1.add(subjectradio);
        subjectradio.setText("Subject");

        buttonGroup1.add(titleradio);
        titleradio.setText("Title");

        buttonGroup1.add(authorradio);
        authorradio.setText("Author");

        buttonGroup1.add(idradio);
        idradio.setText("Book ID");

        buttonGroup1.add(isbnradio);
        isbnradio.setText("ISBN");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(subjectradio)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleradio)
                                .addGap(18, 18, 18)
                                .addComponent(authorradio)
                                .addGap(18, 18, 18)
                                .addComponent(idradio)
                                .addGap(18, 18, 18)
                                .addComponent(isbnradio))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jButton1)
                        .addGap(92, 92, 92)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(subjectradio)
                    .addComponent(titleradio)
                    .addComponent(authorradio)
                    .addComponent(idradio)
                    .addComponent(isbnradio))
                .addGap(18, 18, 18)
                .addComponent(searchfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        search();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        new Librarian().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed
public void search(){
    
        try{
            String query = null;
        if (subjectradio.isSelected()){
            query = "SELECT * FROM books WHERE subject = ?";
        } else if(titleradio.isSelected()){
            query = "SELECT * FROM books WHERE title = ?";
        } else if (authorradio.isSelected()){
            query = "SELECT * FROM books WHERE author = ?";
        } else if (idradio.isSelected()){
            query = "SELECT * FROM books WHERE bookID = ?";
        } else if(isbnradio.isSelected()){
            query = "SELECT * FROM books WHERE isbn = ?";
        }
            ps =con.prepareStatement(query);
            if (subjectradio.isSelected()){
            ps.setString(1, searchfield.getText());
        } else if(titleradio.isSelected()){
             ps.setString(1, searchfield.getText());
        } else if (authorradio.isSelected()){
             ps.setString(1, searchfield.getText());
        } else if (idradio.isSelected()){
             ps.setInt(1, Integer.parseInt(searchfield.getText()));
        } else if(isbnradio.isSelected()){
            ps.setInt(1, Integer.parseInt(searchfield.getText()));
        } 
            rs = ps.executeQuery();
            jTable2.setModel(new DefaultTableModel(null, new String[]{"Subject","Title", "Author", "ID", "ISBN"}));
            while(rs.next()){
             String author = rs.getString("author");
             String subject = rs.getString("subject");
             String title = rs.getString("title");
             int bookId = rs.getInt("bookID");
             int isbn = rs.getInt("isbn");
             String tableData[] = {subject, title, author, String.valueOf(bookId), String.valueOf(isbn)};
             DefaultTableModel defaultModel = (DefaultTableModel) jTable2.getModel();
             defaultModel.addRow(tableData);
            }
            
        } catch (SQLException ex) { 
        Logger.getLogger(BookFrom.class.getName()).log(Level.SEVERE, null, ex);
    } 
}
    public  void tableData(){
    String query = "SELECT * FROM books";
        try{
           
        BookFrom booksform = new BookFrom();
        booksform.setVisible(true);
        
         ps = con.prepareStatement(query);
         rs = ps.executeQuery();
         while (rs.next()){
             String author = rs.getString("author");
             String subject = rs.getString("subject");
             String title = rs.getString("title");
             String bookId = String.valueOf(rs.getInt("bookID"));
             String isbn = String.valueOf(rs.getInt("isbn"));
             String tableData[] = {subject, title, author, bookId, isbn};
             DefaultTableModel defaultModel = (DefaultTableModel) booksform.jTable2.getModel();
             defaultModel.addRow(tableData);
         }
        
        } catch (SQLException ex) { 
        Logger.getLogger(student_form.class.getName()).log(Level.SEVERE, null, ex);
    } 
    }             

    /**
     * @param args the command line arguments*
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookFrom().setVisible(true);
                                         
}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton authorradio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton idradio;
    private javax.swing.JRadioButton isbnradio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable2;
    private javax.swing.JTextField searchfield;
    private javax.swing.JRadioButton subjectradio;
    private javax.swing.JRadioButton titleradio;
    // End of variables declaration//GEN-END:variables
}
